version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  reviewers:
  - ChristophWurst
  ignore:
  - dependency-name: rubix/ml
    versions:
    - 0.3.2
    - 0.4.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  reviewers:
  - ChristophWurst
  labels:
  - 3. to review
  - dependencies
  - javascript
  ignore:
  - dependency-name: chart.js
    versions:
    - 3.0.1
    - 3.0.2
  - dependency-name: webpack
    versions:
    - 5.21.0
